apiVersion: v1
kind: Service
metadata:
  name: k8-service
  labels:
    app: k8-service
spec:
  selector:
    app: k8
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud

