services:
  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '${PORT:-5000}:5000'
    env_file:
      - .env.dev
    networks:
      - acquisitions-dev
    volumes:
      # Mount source code for developemnt hot-reload
      - .:/app
      - /app/node_modules
      - ./src/drizzle:/app/src/drizzle
      - ./src/logs:/app/logs
    restart: unless-stopped
    user: root
    profiles:
      - dev

networks:
  acquisitions-dev:
    driver: bridge
